general {
    # Força o foco total do teclado ao abrir o launcher
    grab_focus = true
}

cache {
    # Mantém um histórico/cache dos itens mais acessados em ~/.local/share/hyprlauncher
    enabled = true
}

finders {
    # Finder padrão ativo ao abrir ( desktop , unicode , math )
    default_finder = desktop

    # Prefixos de acionamento rápido para mudar de modo (deve ser apenas 1 caractere)
    desktop_prefix = 
    unicode_prefix = .
    math_prefix = =
    font_prefix = '

    # Prefixo de inicialização de apps desktop (ex: "uwsm app --" se usar UWSM)
    desktop_launch_prefix = 

    # Exibir ícones dos aplicativos nos resultados
    desktop_icons = true
}

ui {
    # Tamanho padrão da janela do launcher (largura e altura)
    window_size = 400 260
}